### ISSUE TITLE
Bootstrap Django project

### ISSUE THREAD

**Issue by codingtenshi** [codingtenshi/namecie#1]
- set up basic project
- when navigation to root i should see the description of project, top right corner should be login button
- clicking sign in should navigate me to `/login`

**Comment by Parham-Mehrabi** [comment]
hi, I would be happy to help
just to be clear, Do you want it to use Bootstrap or pure CSS?

**Comment by codingtenshi** [comment]
@Parham-Mehrabi bootstrap meant to basically start fresh project. I use Tailwind for CSS. Changes in `master` already.
